apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  # Add a finalizer so ArgoCD can clean up the CRDs when this app is deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    # We'll install the controller in its own namespace
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    # This is the official Helm chart repo for the NGINX Ingress
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "4.10.0" # Pinning to a specific stable version
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Tell ArgoCD to create the 'ingress-nginx' namespace
