apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immoly-ingress
  namespace: immoly
  annotations:
    # We use a sync-wave to ensure this resource is only applied
    # *after* the service it depends on has been created by ArgoCD.
    argocd.argoproj.io/sync-wave: "1"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  # This tells the NGINX controller to manage this Ingress
  ingressClassName: nginx
  rules:
    - host: "immoly.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immoly-app-service
                port:
                  # This must match the 'port' (not targetPort) from the Service
                  number: 80
  tls:
  - hosts:
      - "immoly.io"
    secretName: immoly-tls
