apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: migrations
  name: migrations
  namespace: immoly
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migrations
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: migrations
    spec:
      containers:
        - args:
            - npx
            - drizzle-kit
            - migrate
          envFrom:
            - configMapRef:
                name: env
          image: ghcr.io/davidcode2/immoly-migrations:latest
          name: immoly-migrations
      restartPolicy: Always
